# Generated by Django 5.1.2 on 2024-12-12 14:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('products', '0013_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chartItem',
            new_name='CartItem',
        ),
    ]
