# Generated by Django 5.1.2 on 2025-01-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
