# Generated by Django 5.1.1 on 2025-02-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_order_guest_address_order_guest_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_method',
            new_name='billing_method',
        ),
    ]
