# Generated by Django 5.1.1 on 2025-02-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_rename_payment_method_order_billing_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
