# Generated by Django 5.1.1 on 2025-02-10 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_remove_order_cart_items_order_order_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
