# Generated by Django 5.1.1 on 2025-02-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_remove_orderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
