# Generated by Django 5.1.1 on 2024-10-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('price', models.FloatField(default=0.0)),
                ('body', models.TextField(blank=True)),
                ('slug', models.SlugField(default=models.CharField(max_length=75))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
