# Generated by Django 5.1.2 on 2024-10-18 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='zip_code',
            field=models.CharField(default='00-000', max_length=6, validators=[django.core.validators.RegexValidator(code='invalid_zip_code', message='Popraw kod pocztowy, np. 12-345', regex='^\\d{2}-\\d{3}$')]),
        ),
    ]
