# Generated by Django 5.1.2 on 2024-10-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_clientprofile_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='rodo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='zip_code',
            field=models.CharField(max_length=6),
        ),
    ]
