# Generated by Django 5.1.2 on 2024-10-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_clientprofile_rodo_alter_clientprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
    ]
