# Generated by Django 5.1.2 on 2024-10-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_clientprofile_is_activate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='is_activate',
        ),
    ]
