# Generated by Django 5.1.2 on 2024-10-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_clientprofile_is_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
