# Generated by Django 5.1.2 on 2024-10-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_clientprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
