# Generated by Django 5.1.2 on 2024-12-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_clientprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(default='-', max_length=30),
            preserve_default=False,
        ),
    ]
